# .github/workflows/update_42_projects.yml
name: 🗓️ Actualización Diaria del Perfil 42

on:
  # Ejecución programada: '0 3 * * *' se ejecuta a las 03:00 UTC todos los días.
  # Puedes ajustar la hora si lo deseas (Ej: 0 22 * * * para las 10 PM UTC)
  schedule:
    - cron: '0 3 * * *'

  # Permite la ejecución manual desde la pestaña 'Actions'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout del repositorio
        uses: actions/checkout@v4
        with:
          # Esencial para el paso 'git push'
          fetch-depth: 0 

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Versión recomendada

      - name: 📦 Instalar dependencias (requests)
        run: |
          python -m pip install --upgrade pip
          # 🚨 CAMBIO CLAVE: Instala 'requests' directamente en lugar de usar -r requirements.txt
          pip install requests

      - name: ⚙️ Ejecutar script de actualización
        env:
          # Carga los secretos y el login de 42
          FT_CLIENT_ID: ${{ secrets.FT_CLIENT_ID }}
          FT_CLIENT_SECRET: ${{ secrets.FT_CLIENT_SECRET }}
          FT_42_LOGIN: ${{ secrets.FT_42_LOGIN }}
        # 🚨 IMPORTANTE: Usa el nombre de archivo correcto
        run: python ./scripts/update_42_projects.py 

      - name: 💾 Commit y Push del README (Ignorando token.json)
        run: |
          # 1. Configurar la identidad
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          
          # 2. Añadir EXPLICITAMENTE solo el README.md
          git add README.md
          
          # 3. Comprobar si hay cambios y hacer commit/push solo si es necesario
          if git diff --cached --quiet; then
            echo "El README.md no ha cambiado. Terminando sin commit."
          else
            git commit -m "🤖 Actualización automática del progreso de 42."
            git push
          fi
